basedatos:
  path: .\tienda.db
almacen:
  servidor: localhost
  puerto: 5000
consumidor:
  nombre: User01
tables:
  articles:
    columns:
      id:
        type: INTEGER PRIMARY KEY
      name:
        type: TEXT
      price:
        type: REAL
      amount:
        type: INTEGER
      sales:
        type: INTEGER